# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "UnblendedCost", # <aws_billing>
  "BlendedCost", # <aws_billing>
  "service_map", # <billing_factory>
  "acronym", # <billing_factory>
  "Service", # <billing_factory>
  "DBInstanceArn", # <aws_db_rds_list>
  ".", # <aws_group>
  ".", # <aws_policy>
  "type", # <aws_policy_list_entities>
  ".", # <aws_role>
  "user", # <aws_bucket_remove_user>
  "user", # <aws_bucket_get_permissions>
  "permissions", # <aws_bucket_get_permissions>
  "PolicyArn", # <permissions_user_bucket>
  "resource_arn", # <permissions_user_bucket>
  "group", # <permissions_groups>
  "arn", # <aws_secrets_all>
  "created_date", # <aws_secrets_all>
  "secret_raw", # <aws_secrets_rotate>
  "secret_str", # <aws_secrets_rotate>
  "name", # <ui_fetch_secret>
  "PasswordLastUsed", # <user_list_tidy>
  "CreateDate", # <tidy_generator>
  "IpPermissions", # <security_group_handler>
  NULL
))
